target("bazel-cuda-target.basic", function()
    set_kind("binary")
    add_files("basic/kernel.cu")
    add_files("basic/main.cc")
    -- 自动探测当前主机的 cuda 设备, 快速匹配到对应的 gencode 设置追加到构建命令中
    add_cugencodes("native")
end)

target("bazel-cuda-target.basic-macros", function()
    set_kind("binary")
    add_files("basic-macros/main.cu")
    add_cugencodes("native")
end)

target("bazel-cuda-target.cublas", function()
    set_kind("binary")
    add_files("cublas/cublas.cc")
    add_sysincludedirs("/usr/local/cuda-11.8/targets/x86_64-linux/include")
    add_syslinks("cublas")
end)

target("bazel-cuda-target.if-cuda", function()
    set_kind("binary")
    add_files("if-cuda/kernel.cu", "if-cuda/main.cc")
    add_defines("CUDA_ENABLED")
end)

target("bazel-cuda-target.rdc", function()
    set_kind("binary")
    add_files("rdc/*.cu")
end)

target("bazel-cuda-target.thrust", function()
    set_kind("binary")
    add_files("thrust/thrust.cu")
end)
