name:
  Run CMake Example 

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  build:
    container: nvcr.io/nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04
    runs-on: ubuntu-24.04
    steps:
      - name: Prepare Environment
        run: |
          apt-get update
          apt-get install -y --fix-missing build-essential git git-lfs sudo \
            cmake make clang libboost-all-dev ninja-build cppcheck clang-tools \
            clang-format protobuf-compiler

      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: true

      - name: Print Current Path
        run: pwd

      - name: Run CMake Examples
        run: |
          bash scripts/run_cmake_examples.sh
