name:
  Publish Docker Image
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]
  release:
    types: [ published ]


  # 按 tag 推送时
  # push:
  #   tags:
  #     - "v*.*.*"
  #     - "v*.*.*-*"

jobs:
  publish:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
              - registry: docker.io
                username: DOCKER_USERNAME
                password: DOCKER_PASSWORD
                image: docker4cat/zxmake-examples

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ matrix.registry }}
          username: ${{ secrets[matrix.username] }}
          password: ${{ secrets[matrix.password] }}

      - name: Extract Docker metadata
        id: meta
        # uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.image }}
          flavor: |
              latest=true
              prefix=
              suffix=
  
      - name: Build and push Docker image
        id: build-and-push
        # uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        uses: docker/build-push-action@v4
        with:
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
