name:
  Run XMake Example 

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  build:
    container: nvcr.io/nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04
    runs-on: ubuntu-24.04
    steps:
      - name: Prepare Environment
        run: |
          apt-get update
          apt-get install -y --fix-missing build-essential git git-lfs \
            cmake make clang sudo curl wget ccache g++-aarch64-linux-gnu \
            unzip llvm protobuf-compiler
          
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: true

      - name: Install XMake
        run: |
          mkdir /software && cd /software
          git clone --recursive https://github.com/TOMO-CAT/xmake.git
          cd xmake
          git checkout master
          bash scripts/install.sh
          xmake --version
          
      - name: Install Zig
        env:
          ZIG_VER: 0.14.0
        run: |
          mkdir /software && cd /software
          curl https://ziglang.org/builds/zig-linux-$(uname -m)-${ZIG_VER}.tar.xz -o zig-linux.tar.xz
          tar xf zig-linux.tar.xz
          mv zig-linux-$(uname -m)-${ZIG_VER}/ /opt/zig

      - name: Print Current Path
        run: pwd

      - name: Run XMake Examples
        run: |
          bash scripts/run_xmake_examples.sh
