name:
  Run XMake Example 

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  build:
    container: nvcr.io/nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04
    runs-on: ubuntu-24.04
    steps:
      - name: Prepare Environment
        run: |
          apt-get update
          apt-get install -y --fix-missing build-essential git git-lfs \
            cmake make clang sudo
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: true
