name:
  Run XMake Example 

on:
  workflow_dispatch:

jobs:
  build:
    container: nvcr.io/nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Prepare Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y --fix-missing build-essential git \
            cmake make clang
